-- MySQL Script generated by MySQL Workbench
-- 11/02/17 20:55:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store` DEFAULT CHARACTER SET utf8 ;
USE `store` ;

-- -----------------------------------------------------
-- Table `store`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`Account` (
  `uid` INT NOT NULL,
  `username` NVARCHAR(45) NULL,
  `password` CHAR(32) NULL,
  `sex` VARCHAR(45) NULL,
  `age` INT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`Address` (
  `aid` INT NOT NULL AUTO_INCREMENT,
  `province` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `uid` INT NULL,
  PRIMARY KEY (`aid`),
  INDEX `fk_account_idx` (`uid` ASC),
  CONSTRAINT `fk_account`
    FOREIGN KEY (`uid`)
    REFERENCES `store`.`Account` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`Orders` (
  `oid` INT NOT NULL AUTO_INCREMENT,
  `orderDate` DATE NOT NULL,
  `totalPrice` DECIMAL(20) NOT NULL,
  `uid` INT NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `state` INT NULL,
  PRIMARY KEY (`oid`),
  INDEX `fk_account_idx` (`uid` ASC),
  CONSTRAINT `fk_account_order`
    FOREIGN KEY (`uid`)
    REFERENCES `store`.`Account` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`Category` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `cname` NVARCHAR(20) NULL,
  `cdescription` NVARCHAR(50) NULL,
  PRIMARY KEY (`cid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`Product` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `pname` NVARCHAR(20) NULL,
  `cid` INT NULL,
  `price` DECIMAL(20) NULL,
  `pdescription` NVARCHAR(45) NULL,
  `psales` INT NULL,
  `pic` NVARCHAR(45) NULL,
  `pquantity` INT NULL,
  PRIMARY KEY (`pid`),
  INDEX `fk_category_idx` (`cid` ASC),
  CONSTRAINT `fk_category`
    FOREIGN KEY (`cid`)
    REFERENCES `store`.`Category` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`Cart` (
  `cartid` INT NOT NULL,
  `pid` INT NOT NULL,
  `pquantity` INT NULL,
  PRIMARY KEY (`cartid`, `pid`),
  INDEX `fk_product_cart_idx` (`pid` ASC),
  CONSTRAINT `fk_acount_cart`
    FOREIGN KEY (`cartid`)
    REFERENCES `store`.`Account` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_cart`
    FOREIGN KEY (`pid`)
    REFERENCES `store`.`Product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`Items` (
  `oid` INT NOT NULL,
  `pid` INT NOT NULL,
  `quantity` INT NULL,
  `num` INT NULL,
  `total` DECIMAL(20) NULL,
  PRIMARY KEY (`oid`, `pid`),
  INDEX `fk_item_product_idx` (`pid` ASC),
  CONSTRAINT `fk_item_order`
    FOREIGN KEY (`oid`)
    REFERENCES `store`.`Orders` (`oid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_product`
    FOREIGN KEY (`pid`)
    REFERENCES `store`.`Product` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
